### ISSUE TITLE
Hurstville and Kogarah DA sites are now in a new one

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/multiple_masterview#3]
The new site is not a masterview site

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_27had)

**Comment by tuppa** [comment]
@mlandauer been trying to reach out via contacts@planningalerts.org.au, but not hearing from anyone so far.

Anyway, I've written a scraper for GRC in Python here: https://morph.io/tuppa/georges_river_council_etrack

**Comment by mlandauer** [comment]
@tuppa has instead created a PR which fixes this issue by updating the icon scraper https://github.com/planningalerts-scrapers/icon_scraper/pull/9
